export enum FactType {
  HIGH_SPEND_ZERO_CONVERSIONS = 'HIGH_SPEND_ZERO_CONVERSIONS',
  LOW_CTR = 'LOW_CTR',
  HIGH_CPC = 'HIGH_CPC',
  HIGH_CPA = 'HIGH_CPA',
  LOW_ROAS = 'LOW_ROAS',
  KEYWORD_WASTE = 'KEYWORD_WASTE',
  SCALING_OPPORTUNITY = 'SCALING_OPPORTUNITY',
  DATA_QUALITY_WARNING = 'DATA_QUALITY_WARNING',
}
