export enum ImportStatus {
  PENDING = 'PENDING',
  PROCESSING_BRONZE = 'PROCESSING_BRONZE',
  PROCESSING_SILVER = 'PROCESSING_SILVER',
  PROCESSING_GOLD = 'PROCESSING_GOLD',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
