export enum RawFileStatus {
  UPLOADED = 'UPLOADED',
  PROFILING = 'PROFILING',
  PROFILED = 'PROFILED',
  AUTO_CLASSIFIED = 'AUTO_CLASSIFIED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  READY_TO_PROCESS = 'READY_TO_PROCESS',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
