import { AppsFlyerReportType } from '../enums/appsflyer-report-type.enum';
import { CanonicalEventType } from '../enums/canonical-event-type.enum';
import { Platform } from '../enums/platform.enum';
import type { AppsFlyerEventValuePayload } from './appsflyer-event-value-payload.contract';

export type NormalizedAppsFlyerEvent = {
  projectId: string;
  integrationId: string;
  importId: string;
  source: Platform.APPSFLYER;
  reportType: AppsFlyerReportType;
  eventName: string;
  canonicalEventName: CanonicalEventType;
  eventTime?: string;
  eventDate: string;
  installTime?: string;
  attributedTouchTime?: string;
  mediaSource?: string;
  campaignName?: string;
  campaignId?: string;
  adsetName?: string;
  adsetId?: string;
  adName?: string;
  adId?: string;
  countryCode?: string;
  platform?: string;
  appsflyerId?: string;
  customerUserId?: string;
  advertisingId?: string;
  eventAmount?: number;
  eventRevenue?: number;
  currency?: string;
  isRetargeting?: boolean;
  isBlocked?: boolean;
  blockedReason?: string;
  blockedSubReason?: string;
  rejectedReason?: string;
  eventValue?: AppsFlyerEventValuePayload;
  rawPayload: Record<string, unknown>;
  rowHash: string;
  ingestionVersion: string;
};
