import { AppsFlyerReportType } from '../enums/appsflyer-report-type.enum';
import { CanonicalEventType } from '../enums/canonical-event-type.enum';
import { DataSource } from '../enums/data-source.enum';
import type { AppsFlyerEventValuePayload } from './appsflyer-event-value-payload.contract';

export type NormalizedAppsFlyerEvent = {
  projectId: string;
  integrationId?: string | null;
  importId: string;
  rawFileId: string;
  source: DataSource.APPSFLYER;
  reportType: AppsFlyerReportType | string;
  eventName: string;
  canonicalEventName: CanonicalEventType;
  eventTime?: string | null;
  eventDate: string;
  installTime?: string | null;
  attributedTouchType?: string | null;
  attributedTouchTime?: string | null;
  mediaSource?: string | null;
  partner?: string | null;
  channel?: string | null;
  campaignName?: string | null;
  campaignId?: string | null;
  adsetName?: string | null;
  adsetId?: string | null;
  adName?: string | null;
  adId?: string | null;
  countryCode?: string | null;
  region?: string | null;
  state?: string | null;
  city?: string | null;
  platform?: string | null;
  appsflyerId?: string | null;
  customerUserId?: string | null;
  advertisingId?: string | null;
  isRetargeting?: boolean;
  retargetingConversionType?: string | null;
  isBlocked?: boolean;
  blockedReason?: string | null;
  blockedSubReason?: string | null;
  rejectedReason?: string | null;
  eventAmount?: number | null;
  eventRevenue?: number | null;
  currency?: string | null;
  eventValue?: AppsFlyerEventValuePayload;
  rawPayload: Record<string, unknown>;
  rowHash: string;
  ingestionVersion?: string;
};
